// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrj2sfL869qgc_a03f5_GvtgNnCcx-ixg',
    appId: '1:366036719523:web:95cdaff3821410a6d42c16',
    messagingSenderId: '366036719523',
    projectId: 'project-oshiro-ff1d0',
    authDomain: 'project-oshiro-ff1d0.firebaseapp.com',
    storageBucket: 'project-oshiro-ff1d0.appspot.com',
    measurementId: 'G-15M2KQ7X40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQIllugn4WoaZLJsjXFavmp73o2cEa8o',
    appId: '1:366036719523:android:a41e8050e9aff677d42c16',
    messagingSenderId: '366036719523',
    projectId: 'project-oshiro-ff1d0',
    storageBucket: 'project-oshiro-ff1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKYf-saxniNyXEYWhhlZ7MsWjik6ZIZI',
    appId: '1:366036719523:ios:565c11f3cb654bdbd42c16',
    messagingSenderId: '366036719523',
    projectId: 'project-oshiro-ff1d0',
    storageBucket: 'project-oshiro-ff1d0.appspot.com',
    iosBundleId: 'dev.calliari.oshiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKYf-saxniNyXEYWhhlZ7MsWjik6ZIZI',
    appId: '1:366036719523:ios:af38bc35dcf5e2b6d42c16',
    messagingSenderId: '366036719523',
    projectId: 'project-oshiro-ff1d0',
    storageBucket: 'project-oshiro-ff1d0.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHAEHbal16QOAxWxSiWCF7P5BVN9SEP-Y',
    appId: '1:366036719523:web:c00e1607a1078bf6d42c16',
    messagingSenderId: '366036719523',
    projectId: 'project-oshiro-ff1d0',
    authDomain: 'project-oshiro-ff1d0.firebaseapp.com',
    storageBucket: 'project-oshiro-ff1d0.appspot.com',
    measurementId: 'G-VKXVGXEXT6',
  );
}
